// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'board': string;
  'board__border': string;
  'board__border--inside': string;
  'board__border--l': string;
  'board__border--v': string;
  'container': string;
  'cursor': string;
  'pieces': string;
  'pieces--black': string;
  'pieces--container': string;
  'pieces--prev': string;
  'pieces--white': string;
  'pieces-demo': string;
  'pieces-demo--black': string;
  'pieces-demo--white': string;
  'reset__lich': string;
  'turn-black': string;
  'turn-white': string;
}
export const cssExports: CssExports;
export default cssExports;
