// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'btn--large': string;
  'btn--radius': string;
  'btn--stripe': string;
  'stripe-slide': string;
}
export const cssExports: CssExports;
export default cssExports;
