// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'msg--close': string;
  'msg--container': string;
  'msg--header': string;
  'msg--text': string;
  'msg--title': string;
  'msg--wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
